development:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: wip_dev
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: ld_test

# We aren't using concurrency, only one process per dyno,
# so we just create 2 connections for every thread to
# be able mitigate connection starvation issues we are
# seeing in production
production:
  encoding: utf8
  pool: <%= Integer(ENV.fetch('RAILS_MAX_THREADS', 5)) * 2 %>
  reconnect: true
