name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.6.5

    steps:
    - uses: actions/checkout@v1

    - name: Cache Gems
      uses: actions/cache@v1
      with:
        path: /usr/local/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Install Gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Rubocop
      run: |
        bundle exec rubocop
