name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ruby:2.6.5

    steps:
    - uses: actions/checkout@v1

    - name: install PostgreSQL client
      run: apt-get install libpq-dev

    - name: Install Gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Rubocop
      run: |
        bundle exec rubocop
